EnterpriseDB/tpa

docs/src/INSTALL-docker.md, docs/src/INSTALL-repo.md
The repo is now called tpa.git, so change explcit references to the repo name, and change references to the directory it creates
=> Correct repo name in docs

platforms/docker/docker_image.yml
When using the intermediate base docker image option use the name of the image plus the tag to construct the `BASE_IMAGE` arg to the final image builder.
It appears that the digest form `sha256:xxxx` only works when an image has a digest, which is created when an image is pushed to a v2 registry. An image that is built locally will have no digest and specifying one will force the docker daemon to attempt to retrieve the image from a registry.
References: TPA-536
=> Construct `base_image` from the image name plus the tag in a fact

roles/postgres/service/tasks/main.yml, roles/postgres/service/templates/postgres.service.j2
Symbolic link for `postmaster` has been removed in pg16. Previous versions support the arguments to start the daemon.
References: TPA-547
=> Use postgres binary instead of postmaster

.github/workflows/integration_tests.yml, .github/workflows/requirements.yml, .github/workflows/simple_integration_tests.yml, .github/workflows/simple_patroni_integration_tests.yml, .github/workflows/unit_tests.yml
As the master branch name changed to main during the repo change of tpa, we need to update the branch references in GitHub workflows. These jobs aren't triggering at the moment.
=> Update `master` to `main` branch name change on new repo

roles/sys/repositories/tasks/os/RedHat/repositories.yml
The packages (e.g., barman) have to come from somewhere, so if we're not
going to provide them, we can't also refuse to use them from PGDG. Note
that this also doesn't apply to community_360, which doesn't yet have
the packages it needs, and so depends on PGDG.
References: TPA-545
=> Don't exclude packages from PGDG if no EDB repositories are in use

roles/postgres/config/vars/conf_extensions.yml
Postgres configuration `facts` only support a single key/value level and should not have values with nested dictionaries. Any values passed to Patroni will be ignored and will result in warning messages in the log.
Extensions have a configuration format of:
extension_name.config_key: "value"
References: TPA-564
=> Flatten configuration keys for extensions in postgres config

roles/test/tasks/bdr/config.yml
adding a schema selection for some tests that look for bdr config such as:
- bdr.standby_slot_names check
- bdr.standby_slots_min_confirmed check
that would live in pglogical schema in BDR3 but got added to bdr in later bdr version (4, 5)
=> TPA-527: use different schema for bdr3

Dockerfile, entrypoint.sh
- Update base image of Debian to bullseye.
- Install whichever generic python3 version. Note TPA is not fully tested with python3.11.
- Remove add-apt-repository as it didn't work and lowers package footprint.
- Install community ansible by default.
- Add an entrypoint script that can reset permissions of files created on exit.
=> Update docker image

roles/test/tasks/pg-backup-api.yml
Add `become: yes` to one of the pg-backup-api test tasks so that it runs as root even when `ansible_user` is another user.
References: TPA-471
=> Run pg-backup-api tests as root

roles/pem/server/config/webserver/handlers/main.yml, roles/pem/server/config/webserver/tasks/main.yml, roles/pem/server/config/webserver/tasks/pem_sites.yml
When installing and configuring apache on a PEM server, we need to enable it explicitly so that systems (currently RHEL) on which this isn't the default do the right thing.
=> Enable apache on PEM servers

lib/tpaexec/architecture.py
Explicitly set tpa_2q_repositories to be empty in config.yml if postgres_version >= 16 and no 2q repositories have been explicitly asked for in the invocation of `tpaexec configure`. This suppresses the behaviour we would otherwise get at deploy-time whereby the `dl/default/release` repository would be added; this repository doesn't exist for postgres 16.
References: TPA-577
=> Avoid attempting to use non-existent 2q repos

roles/init/tasks/postgres.yml, roles/postgres/replica/final/tasks/main.yml
Some customers might need to stay with repmgr for different reasons. Without this TPA was setting the failover_manager as none when someone want to go down this path. One of the reasons is if inside a bdr cluster a node is required to work as a replica of a subscriber-only host, in that case only, tpa will allow repmgr to be installed and configured.
=> Accept `repmgr` as failover_manager in BDR when a replica is required.

platforms/docker/docker_image.yml
Previous to this commit TPA was failing to execute `tpaexec deploy` or `tpaexec download-packages` for clusters attempting to use the Docker image `tpa/ubuntu:jammy`. The following error was observed:
```
Please specify build instructions for ubuntu:jammy in docker_images
```
The issue was caused because of a typo in the mapping specified inside `platforms/docker/docker_image.yml`.
This commit fixes that issue.
References: TPA-594.
=> Fix `docker build` of `tpa/ubuntu:jammy` image

roles/sys/repositories/tasks/os/Debian/edb-repositories.yml, roles/sys/repositories/tasks/os/RedHat/repositories.yml, roles/sys/repositories/tasks/os/SUSE/repositories.yml
We need to ensure that EDB repos defined in the config file are the one added to the cluster nodes and that any change to the configuration file will be taken into account. removing a repo from config.yml should remove the definition on the node available repositories list the same way we do for legacy 2Q repositories.
=> TPA-529: remove unused EDB repo definition after config change

roles/harp/config/tasks/harp2.yml, roles/harp/config/templates/harp2.config.j2, roles/harp/service/tasks/main.yml, roles/harp/service/templates/harp.service.j2
Ensure that both harp-proxy and harp-manager are correctly configured when both roles are cohosted on a node.
Use a different config file for proxy when cohost is detected. proxy-config.yml is used and service file override is set accordingly.
Fix non detected bug for harp service file override also for cohosted proxy
where override for manager would also be applied to proxy service.
Clean up unused vars set for harp config templating leftover from TPA-72 split of tasks
=> TPA-554: Fix Cohost harp proxy/manager config

architectures/BDR-Always-ON/commands/upgrade.yml, architectures/M1/commands/upgrade.yml
Add repository configuration to upgrade playbooks (BDR-Always-ON, M1) to ensure that repositories are updated before upgrade process, especially for local-repo-only clusters.
=> TPA-472: Add repository cleanup to upgrade

docs/src/pem.md, lib/tpaexec/architecture.py
Check for and reject the unsupported combination of the BDR-Always-ON architecture, the EDB Postgres Extended flavour, and PEM in `tpaexec configure`. Document this and very lightly clean the PEM docs.
=> Reject BDR-Always-ON/edbpge/PEM at configure-time

bin/tpaexec, docs/src/INSTALL.md
When `tpaexec setup` is run, it will now default to community ansible rather than 2ndQuadrant ansible. The new option `--use-2q-ansible` will force the old behaviour and trigger a warning message about the deprecation of 2ndQuadrant ansible.
Fixes: TPA-499
=> Make community ansible the default

roles/pem/agent/pkg/defaults/main.yml, roles/pem/server/config/webserver/defaults/main.yml, roles/pem/server/config/webserver/tasks/configure_httpd_module.yml, roles/pem/server/config/webserver/templates/edb-pem.conf.j2, roles/pem/server/pkg/defaults/main.yml, roles/sys/pkg/defaults/main.yml
Add SUSE-family-specific values for the various PEM parameters and required apache configuration.
Fixes: TPA-603
=> Support installing PEM on SLES

docs/src/air-gapped.md
This instruction is no longer relevant as changes in 23.24 mean target instance repos will always be updated from the TPA host when upgrade is run
=> Remove instruction to run deploy before upgrade

roles/pgdcli/config/tasks/main.yml
Add a symlink to the default path for pgdcli config.
This allows use of pgdcli without adding `-f` switch for pgdcli v1.
=> TPA-462: create symlink to cli default config path

bin/tpaexec
Without this, bash is handling some of the words in the heredoc as commands. Replacing the backtick by single quotes to keep the same format along the file.
[root@d0afd2ae4168 /]# /opt/EDB/TPA/bin/tpaexec setup --use-2q-ansible /opt/EDB/TPA/bin/tpaexec: line 273: tpaexec: command not found /opt/EDB/TPA/bin/tpaexec: line 273: --skip-tags: command not found
=> bin/tpaexec: using single quotes in the notification.

architectures/BDR-Always-ON/commands/upgrade.yml, roles/postgres/bdr/tasks/bdr4/post-join.yml
Add a step to set node_kind for nodes during 4.3+ deployments It is recommended to set node_kind starting 4.3
since it takes care of certain issues and is a required step to later upgrade to PGD5.
Add node_kind task to bdr4 upgrade process
set the node_kind during upgrade to bdr4.3+
the task is in a separate task list to ensure
all node were upgraded before trying to set node_kind. we check bdr_version_num to get updated value instead of cluster_facts that still hold pre upgrade value.
=> TPA-587: set node_kind for bdr4

lib/tpaexec/architecture.py, lib/tpaexec/platforms/aws.py, platforms/docker/docker_image.yml, roles/efm/pkg/defaults/main.yml, roles/sys/repositories/tasks/os/SUSE/repositories.yml, roles/sys/sysctl/tasks/os/SUSE.yml
Use sp5 aws ami and docker image when SLES 15 is requested.
Fix repository priorities for SLES so that EDB repositories have priority over PGDG ones, which have priority over vendor ones. Add sp5 aws ami; change default sles 15 docker image to sp5; fix repository priorities so that edb repos have priority over PGDG, which have priority over SUSE-provided repos.
Change configure-time repository selection logic so that EDB repositories can be used on systems such as SLES 15 that don't support 2q repositories, without always having to specify them on the command line.
Support installing EFM on SLES.
Fixes: TPA-604
=> Enhanced SLES 15 support; move to SLES 15sp5

requirements.in
python-certifi is an indirect dependency coming from docker -> requests
-> certifi and by default the version we are getting is pretty old.
Added certifi explicitly to requirements.in so we always pull the latest
compatible version. We can remove it later after we upgrade our basic
python version compatibilty from Python 3.6 (needed for compatibility
with older platforms like RHEL7) to something more recent.
Signed-off-by: Muhammad Haroon <muhammad.haroon@enterprisedb.com>
=> Add python-certifi to requirements.in

architectures/PGD-Always-ON/upgrade_major_3to5.yml, docs/src/tpaexec-upgrade.md
During 3to5 upgrade we run postgres/config role to update configuration files for postgres and bdr including camo.
at this point the node is already running PGD5 but it's cluster_vars haven't yet been updated, template for camo config make use of bdr_version_num and this is part of cluster_vars. we need to set manual value for bdr_version_num since running postgres/facts would require starting postgres withou wrong config, it won't work due to pglogical being missing.
we set bdr_version_num to 503000 which is the minimum required to upgrade from bdr3 to pgd5.
see TPA-614 for error message.
Somehting similar could happen to 4to5 upgrade later if a new config for PGD5.3+ appears.
=> TPA-614: Fix camo upgrade for 3 to 5 upgrade

docs/src/reconciling-local-changes.md
Add a page that describes the consequences of making local changes to a TPA-managed cluster and how one might recover from such a situation. This is not intended to be exhaustive, but to go some way to filling the void of documentation around such situations.
=> Add reconciling local changes doc

bin/tpaexec
When options that will suppress the actual deployment run are given to `tpaexec deploy`, don't automatically run provision beforehand.
Fixes: TPA-558
=> Suppress automatic provision for some deploy options

roles/postgres/bdr/tasks/fence.yml, roles/postgres/bdr/tasks/unfence.yml
Use the bdr_node_name instead of inventory_hostname. 
Specify node_name for fence and unfence commands to avoid failure and ensure bdr_node_name is used even if this should be the default used via config file.
=> TPA-592: fix fence/unfence/get node to use bdr_node_name

Dockerfile
Update `Dockerfile` so the Docker image build succeeds on Mac OS X (Apple Silicon).
Fixes: TPA-616
=> TPA-617: Dockerfile: Enable building on Mac OS X (Apple Silicon)

RELNOTES.md, docs/src/tpaexec-configure.md, lib/tpaexec/architecture.py, lib/tpaexec/architectures/bdr.py, lib/tpaexec/architectures/m1.py
Add an option "--cluster-prefixed-hostnames" to "tpaexec configure", which causes all hostnames to have the cluster name prepended. This avoids hostname clashes when deploying more than one docker cluster simultaneously on the same host.
=> Enable clustername-prefixed hostnames

roles/init/tasks/roles.yml
When having multiple pemservers in a cluster we can't rely on using the first pemserver of the group for nodes with pemserver role. 
pemserver agent needs to always register to it's own pemserver instance.
=> TPA-608: fix pemserver agent registration

architectures/lib/commands/relink
Remove use of the `capture_output` argument to `subprocess.run` in `tpaexec relink`.
=> Remove python 3.7-specific code

architectures/PGD-Always-ON/upgrade_major_3to5.yml, library/minimal_postgres_setup, roles/postgres/update/tasks/preconfig.yml
Fix camo config issue during upgrade from bdr3 to pgd5 using
minimal_postgres_setup module and bdr_config command.
The fix is to update bdr_version facts via minimal_postgres_setup module
before running postgres/config role. it will ensure the correct config
options are set in postgres conf.d/*-camo.conf
Add feature in the minimal_postgres_setup to run bdr_config command and
extract bdr_version_num, bdr_major_version from its output.
This fix should also be used for 4to5 even if there is no breaking conf
set in this case for now.
=> TPA-614: Fix camo enabled cluster upgrade from BDR3 to PGD5

roles/sys/repositories/tasks/os/SUSE/repositories.yml
For EPAS on SLES, we need packages that are only available through SLES's PackageHub repositories, which require the system to be registered. We check if this is a registered system, and if isn't, look in the environment for a registration token and use it to register the system.
=> Install needed repositories to enable EPAS on SLES

roles/postgres/config/templates/tpa.conf.j2, roles/postgres/config/vars/conf_tpa.yml
This greatly reduces the chance of hard failures, while causing only slight slowdown even on very large systems.
Fixes: TPA-629
=> Set maintenance_work_mem to 64MB by default

RELNOTES.md, lib/tpa/instance.py, lib/tpa/transmogrifiers/bdr4pgd5.py
Take already existing bdr3 or bdr4 config into account for generating commit_scope during reconfigure to pgd5.
Ensure we use already defined `synchronous_replication_availability` and `bdr.global_commit_timeout` from bdr3 or bdr4 cluster to generate the pgd5 commit scope for CAMO enabled nodes.
Adjust default commit_scope rule values to match recommended values from BDR/testing team:
- timeout `60s`
- use `require_write_lead = true`
remove the unused bdr3/bdr4 vars mentioned above from config.yml file once we are done creating camo commit_scope.
=> TPA-626: upgrade commit scope generation improvements

RELNOTES.md, roles/postgres/config/tasks/main.yml
Generate a primary_slot_name on primary node when using efm so that it can be used on `switchover` to ensure the use of a physical slot for the original primary on the new primary node.
=> TPA-618: EFM primary_slot_name

.github/actions/install-requirements/action.yml, bin/tpaexec, docs/src/INSTALL-docker.md, docs/src/INSTALL-repo.md, docs/src/INSTALL.md, roles/selftest/tasks/main.yml, runtime.txt
We maintain backwards compatibility with Python 3.6 so far, because both
RHEL7 and RHEL8 have that version by default. But with the cryptography
module removing support for that version, and several pending security
alerts, we want to begin moving away from 3.6 ourselves.
This commit sets the stage for automatically discovering another Python
interpreter (e.g., from edb-python, if available) if the system's
default one is too old. Otherwise, if you initialise your venv with a
different interpreter, or another python is in your PATH, it should just
work sensibly without further ado.
References: TPA-562
=> Require Python 3.9+ when running bin/tpaexec

roles/init/tasks/repos.yml
The new variable "disable_repository_checks" can be set to true in config.yml to bypass the usual check for EDB repositories when deploying the PGD-Always-ON architecture.
Fixes: TPA-616
=> Enable disabling repository checks

roles/barman/templates/barman.d.conf.j2, roles/init/tasks/postgres.yml
Enable separate dsn attributes for the streaming barman user, so that users can use 'ssl_mode=verify-full', which means the user name must match the certificate's user and therefore separate certificates are needed for separate users.
Fixes: TPA-637
=> Separate dsn attributes for streaming barman client

architectures/lib/commands/check-repositories.yml, bin/tpaexec
After running most tpaexec commands, run the new playbook "check-repositories.yml", which does nothing but check the inventory for one host and warn if tpa_2q_repositories is set.
Fixes: TPA-631
=> Warn if 2q repositories are in use

roles/init/tasks/postgres.yml
Removing line feed and trailing blank lines. Otherwise, we might see an error like this:
stderr_lines": ["EXCEPTION: Source contains parsing errors: '/etc/barman.d/machine.conf'", "\t[line  7]: '\"\\n'", "See log file for more details."
=> Fix "streaming_barman_client_dsn_attributes" var

docs/src/bdr.md
Updated link to point to the commit scope reference page rather than a page for a single commit scope (group commit).
=> Point link for comm scope to cs ref

roles/sys/repositories/tasks/os/Debian/2ndquadrant-repository-keys.yml
If there are 2q repositories on a Debian-family instance but the repository keys required for using those repositories after 2020 are not installed, error out instead of trying to install them from what's now an unsupported source.
Fixes: TPA-642
=> Error out instead of grabbing 2q repo keys

lib/tpaexec/architecture.py
When the --cluster-prefixed-hostnames argument is given to `tpaexec configure`, use a version of the cluster name that doesn't contain characters that aren't valid in hostnames.
Fixes: TPA-644
=> Sanitise hostnames with --cluster-prefixed-hostnames

roles/repmgr/pkg/tasks/list-packages.yml
If we're installing repmgr on a RedHat-family system from PGDG repos, the package will be named repmgr_nn not repmgrnn .
Fixes: TPA-576
=> Use correct package names for repmgr in PGDG repos

architectures/lib/commands/check-repositories.yml, bin/tpaexec
If the `assert` task that checks we're not still using 2ndQuadrant repositories fails, the eventual exit status from tpaexec should still reflect the status of the action that the user asked for.
=> Exit correctly if repo check fails

lib/filter_plugins/fnmatch.py, roles/pkg/download/tasks/os/Debian/download.yml, roles/pkg/download/tasks/os/Debian/resolve-package.yml
When using the downloader on a Debian-family system, we now perform our own fnmatch-style globbing on any package versions specified in config.yml, enabling constructions like `bdr_package_version: 4:5.0.*` to behave in the same way as when the downloader is not in use.
Fixes: TPA-463
Fixes: TPA-583
=> Respect package versions in the downloader
